web_shop/auth_users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "auth_users"

urlpatterns = [
    path("register_views/", views.RegisterView.as_view(), name="register_views"),
    path("login_views/", views.UserLoginView.as_view(), name="login_views"),
    path("logout_views/", LogoutView.as_view(next_page="catalog:home_views"), name="logout_views"),
]

web_shop/catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("home_views/", views.ProductListView.as_view(), name="home_views"),
    path("contact_views/", views.ContactTemplateView.as_view(), name="contact_views"),
    path("category_views/", views.CategoryListView.as_view(), name="category_views"),
    path("catalog_views/", views.CatalogProductListView.as_view(), name="catalog_views"),
    path("product_views/<int:pk>/", views.ProductDetailView.as_view(), name="product_views"),
    path("add_product_views/", views.ProductCreateView.as_view(), name="add_product_views"),
    path("update_product_views/<int:pk>/", views.ProductUpdateView.as_view(), name="update_product_views"),
    path(
        "product_views/<int:pk>/delete_product_views/", views.ProductDeleteView.as_view(), name="delete_product_views"
    ),
    path("unauthorized_user_views/", views.UnauthorizedUserListView.as_view(), name="unauthorized_user_views"),
    path("profile_views/<int:pk>/", views.ProfileDetailView.as_view(), name="profile_views"),
    path("update_profile_views/<int:pk>/", views.ProfileUpdateView.as_view(), name="update_profile_views"),
    path("popup_question_views/<int:pk>/", views.ProfilePopupTemplateView.as_view(), name="popup_question_views"),
    path(
        "unpublished_product_views/<int:pk>/", views.UnpublishedProductView.as_view(), name="unpublished_product_views"
    ),
    path("category_detail_views/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail_views"),
]

web_shop/web_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("app_like_photo.urls", namespace="app_like_photo")),
    path("", include("auth_users.urls", namespace="auth_users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_shop/catalog/models.py
from auth_users.models import CustomUser
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование категории")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"
        db_table = "categories"


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Наименование продукта")
    description = models.CharField(max_length=1000, verbose_name="Описание")
    image = models.ImageField(upload_to="photos/")
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, related_name="products", max_length=100, verbose_name="Категория"
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    is_active = models.BooleanField(default=False)
    owner = models.ForeignKey(
        CustomUser,
        on_delete=models.DO_NOTHING,
        related_name="products",
        verbose_name="Пользователь",
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        db_table = "products"
        permissions = [
            ("can_unpublished_product", "Может отменять публикацию продукта"),
        ]


class Contact(models.Model):
    phone_number = models.CharField(max_length=12)
    email = models.EmailField()
    address = models.TextField()

    def __str__(self):
        return f"Телефон - {self.phone_number}"

    class Meta:
        verbose_name = "контакт"
        verbose_name_plural = "контакты"
        db_table = "contacts"

web_shop/catalog/forms.py
from auth_users.models import CustomUser
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from .models import Category, Product


def validate_words(value):
    """Валидация наименования и описания товара на запрещенные слова"""
    banned_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"]
    for banned_word in banned_words:
        if banned_word in value.lower():
            raise ValidationError(
                f'Данное поле не должно содержать следующие слова: "казино", "криптовалюта",\
            "крипта", "биржа", "дешево", "бесплатно", "обман", "полиция", "радар"',
                params={"value": value},
            )


class FormForCreate(forms.ModelForm):
    name = forms.CharField(
        label="Наименование",
        validators=[validate_words],
        widget=forms.TextInput(attrs={"class": "form-control", "style": "width: 400px"}),
    )
    description = forms.CharField(
        label="Описание",
        validators=[validate_words],
        widget=forms.Textarea(attrs={"class": "form-control", "style": "height: 100px"}),
    )
    image = forms.ImageField(
        label="Изображение",
        validators=[FileExtensionValidator(["jpeg", "png"], "Изображение может быть формата: 'jpeg', 'png'")],
        widget=forms.FileInput(attrs={"class": "form-control"}),
    )
    category = forms.ModelChoiceField(
        label="Категория",
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={"class": "form-select", "style": "width: 200px"}),
    )
    price = forms.DecimalField(
        label="Цена", widget=forms.TextInput(attrs={"class": "form-control", "style": "width: 200px"})
    )
    is_active = forms.BooleanField(label="Активность", required=False)

    def clean_price(self):
        """Валидация цены товара"""
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Цена не может быть меньше 0")
        return price

    def clean_image(self):
        """Валидация размера изображения"""
        image = self.cleaned_data.get("image")
        if image.size > 5242880:
            raise ValidationError("Размер изображения не может быть больше 5 mb")
        return image

    class Meta:
        model = Product
        fields = ["name", "description", "image", "category", "price", "is_active"]


class FormUpdateProfile(forms.ModelForm):
    username = forms.CharField(
        label="Наименование",
        widget=forms.TextInput(attrs={"class": "form-control", "style": "width: 400px"}),
    )
    email = forms.EmailField(
        label="Электронная почта", widget=forms.EmailInput(attrs={"class": "form-control", "style": "width: 400px"})
    )
    avatar = forms.ImageField(label="Изображение", widget=forms.FileInput(attrs={"class": "form-control"}))

    class Meta:
        model = CustomUser
        fields = ["username", "email", "avatar"]

web_shop/catalog/views.py
from auth_users.models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .forms import FormForCreate, FormUpdateProfile
from .models import Category, Contact, Product
from .services import CategoryService


@method_decorator(cache_page(60 * 15), name="dispatch")
class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product.html"
    context_object_name = "product"
    success_url = reverse_lazy("catalog:home_views")


class UnpublishedProductView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "catalog.can_unpublished_product"

    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)

        product.is_active = False
        product.save()

        return redirect("catalog:home_views")


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = FormForCreate
    template_name = "catalog/form_add_product.html"
    success_url = reverse_lazy("catalog:home_views")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = FormForCreate
    template_name = "catalog/form_update_product.html"

    def get_success_url(self):
        return reverse_lazy("catalog:product_views", args=[self.kwargs.get("pk")])

    def get_object(self, queryset=None):
        product = super().get_object(queryset)
        user = self.request.user

        if product.owner != user:
            raise PermissionDenied("Вы не можете редактировать этот продукт.")

        return product


class ProductDeleteView(LoginRequiredMixin, PermissionDenied, DeleteView):
    model = Product
    template_name = "catalog/delete_product.html"
    success_url = reverse_lazy("catalog:home_views")

    def get_object(self, queryset=None):
        product = super().get_object(queryset)
        user = self.request.user

        if product.owner != user and not user.has_perm("catalog.delete_product"):
            raise PermissionDenied("Вы не можете удалять этот продукт.")

        return product


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/home.html"
    context_object_name = "products"
    paginate_by = 3

    def get_queryset(self):
        # Получаем только активные объекты
        queryset = cache.get("product_in_category")
        if not queryset:
            queryset = Product.objects.filter(is_active=True)
            cache.set("product_in_category", queryset, 60 * 15)  # Кешируем данные на 15 минут
        return queryset


class CatalogProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "catalog/catalog.html"
    context_object_name = "products"

    def get_queryset(self):
        # Получаем только активные объекты
        return Product.objects.filter(is_active=True)


class UnauthorizedUserListView(ListView):
    model = Product
    template_name = "catalog/unauthorized_user.html"
    context_object_name = "products"


class ContactTemplateView(LoginRequiredMixin, TemplateView):
    model = Contact
    template_name = "catalog/contact.html"
    context_object_name = "contacts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contact"] = Contact.objects.all()[0]
        return context


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = "catalog/category.html"
    context_object_name = "categories"


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    template_name = "catalog/detail_category.html"
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.object.id
        products = CategoryService.get_product_in_category(category_id)
        context["products"] = products
        return context


class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = "catalog/profile.html"
    context_object_name = "profile"


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = FormUpdateProfile
    template_name = "catalog/form_update_profile.html"

    def get_success_url(self):
        return reverse_lazy("catalog:profile_views", args=[self.kwargs.get("pk")])


class ProfilePopupTemplateView(TemplateView):
    model = CustomUser
    template_name = "catalog/popup_question.html"


def custom_permission_denied(request, exception):
    return render(request, "catalog/403.html", {"message": str(exception)})

web_shop/catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Bootstrap demo{% endblock %}</title>
        <link  rel="stylesheet" href="/static/css/bootstrap.min.css"/>
        <style>
            .high {
                height: 100vh;
            }
            .margin-top-main {
                margin-top: 100px;
            }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="col-2">
                {% include 'catalog/nav_bar.html' %}
            </div>
            <div class="col-10">
                {% block content %}{% endblock %}
            </div>
        </div>
        <script src="/static/js/bootstrap.bundle.min.js">
        </script>
    </body>
</html>

web_shop/catalog/templates/catalog/catalog.html
{% extends "catalog/base.html" %}

{% block title %}Каталог{% endblock %}

{% block content %}
<h1 class="text-center margin-top-main mb-5">Каталог</h1>
<div class="row">
    {% for product in products %}
    <div class="col-4 mb-5 d-flex justify-content-evenly">
        <div class="card" style="width: 300px;">
            <img src="{{product.image.url}}" class="card-img-top"
                 alt="...">
            <div class="card-body">
                <p class="card-text">{{ product.name }}.</p>
                <div class="btn-group btn-group-sm position-absolute bottom-0 text-center" role="group"
                     aria-label="Small button group">
                    <a href="{% url 'catalog:product_views' product.pk %}"
                       class="btn btn-outline-primary"> КУПИТЬ {{ product.price }} р.</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

web_shop/catalog/templates/catalog/category.html
{% extends "catalog/base.html" %}

{% block title %}Категории{% endblock %}

{% block content %}
<h1 class="text-center margin-top-main"> Категории </h1>
<div class="row mt-5">
    {% for category in categories %}
    <div class="col-4 mb-5 d-flex justify-content-evenly">
        <div class="card text-center" style="width: 300px;">
            <h5 class="card-header">{{ category.name }}</h5>
            <div class="card-body">
                <a href="{% url 'catalog:category_detail_views' category.pk %}" class="btn btn-outline-primary">Перейти</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

web_shop/catalog/templates/catalog/delete_product.html
<!-- delete_product.html -->
{% extends 'catalog/base.html' %}

{% block title %}Удалить товар{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить товар</h1>
    <p>Вы уверены, что хотите удалить товар?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'catalog:product_views' product.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>

{% endblock %}

web_shop/catalog/templates/catalog/detail_category.html
<!-- home.html -->
{% extends 'catalog/base.html' %}

{% block title %} {{ category.name }} {% endblock %}

{% block content %}

<h1 class="text-center margin-top-main">{{ category.name }}</h1>

<div class="row">
    {% for product in products %}
    <div class="col-5 mb-5 d-flex justify-content-evenly">
        <div class="card" style="width: 350px; margin-top:20px">
            <img src="{{product.image.url}}" class="card-img-top" alt="Изображение">
        </div>
    </div>
    <div class="col-5">
        <div class="card-body">
            <h4 class="card-title text-start" style="margin-top:150px">{{ product.name }}</h4>
            <p class="card-text">{{ product.description }}</p>
            <a href="#" class="btn btn-primary">Купить {{product.price}}p.</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

web_shop/catalog/templates/catalog/nav_bar.html
<!--nav_bar-->

<nav class="navbar sticky-top bg-body-tertiary">
    <div class="container-xxl bg-dark rounded-start high ">
        <a class="navbar-brand link-light border-bottom h4 pb-2 mb-2 border-opacity-50 border-light col-12"
           href="{% url 'catalog:home_views' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                 class="bi bi-bootstrap align-top" viewBox="0 0 16 16">
                <path d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377z"/>
                <path d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3z"/>
            </svg>
            <span class="">
                                Меню
                            </span>
        </a>
        <ul class="nav flex-column margin-bottom">
            <li class="nav-item">
                <a class="nav-link active link-light" aria-current="page" href="{% url 'catalog:home_views' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-house" viewBox="0 0 16 16">-->
                        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                    </svg>
                    <span class="fs-6">
                                        Главная
                                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'catalog:category_views' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-grid" viewBox="0 0 16 16">-->
                        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5z"/>
                    </svg>
                    <span class="fs-6">
                                        Категории
                                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'catalog:catalog_views' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box"
                         viewBox="0 0 16 16">-->
                        <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5 8 5.961 14.154 3.5zM15 4.239l-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464z"/>
                    </svg>
                    <span class="fs-6">
                                        Каталог
                                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'catalog:contact_views' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-person-badge" viewBox="0 0 16 16">-->
                        <path d="M6.5 2a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                        <path d="M4.5 0A2.5 2.5 0 0 0 2 2.5V14a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2.5A2.5 2.5 0 0 0 11.5 0zM3 2.5A1.5 1.5 0 0 1 4.5 1h7A1.5 1.5 0 0 1 13 2.5v10.795a4.2 4.2 0 0 0-.776-.492C11.392 12.387 10.063 12 8 12s-3.392.387-4.224.803a4.2 4.2 0 0 0-.776.492z"/>
                    </svg>
                    <span class="fs-6">
                                        Контакты
                                    </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'catalog:add_product_views' %}">
                    <img src="/media/photos/add_card_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.png" width="20" height="20">

                    <span class="fs-6">
                                        Добавить товар
                                    </span>
                </a>
            </li>
        </ul>
        <div class="dropup-center dropup border-top h4 pt-3 mt-3 border-opacity-50 border-light col-12">
            <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://avatars.mds.yandex.net/get-entity_search/5283930/952851227/S600xU_2x"
                     class="rounded-circle" alt="..." width="30">
                Пользователь
            </button>
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'auth_users:logout_views' %}">
                {% csrf_token %}
                <ul class="dropdown-menu">
                    <button type="submit" class="btn dropdown-item">Выйти</button>
                    <a class="dropdown-item" href="{% url 'catalog:profile_views' user.pk %}">Профиль</a>
                </ul>
            </form>
            {% else %}
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'auth_users:login_views' %}">Войти</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'auth_users:register_views' %}">Регистрация</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

web_shop/catalog/templates/catalog/popup_question.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Изменить</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="container">
                <div class="modal-body">
                    <h5>Вы действительно хотите изменить профиль?</h5>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <a class="btn btn-primary" href="{% url 'catalog:update_profile_views' user.pk %}">Да</a>
            </div>
        </div>
    </div>
</div>

web_shop/catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}

{% block title %}Товар{% endblock %}

{% block content %}
<div class="row">
    <div class="col-5 mb-5 d-flex justify-content-evenly">
        <div class="card" style="width: 350px; margin-top:20px">
            <img src="{{product.image.url}}" class="card-img-top" alt="Изображение">
            <div class="card-body">
                <p class="card-text">{{ product.description }}</p>
                <div class="row">
                    <div class="btn-group" role="group" aria-label="Basic outlined example">
                        {% if product.owner == user %}
                        <a href="{% url 'catalog:home_views' %}" class="btn btn-outline-secondary">Назад</a>
                        <a href="{% url 'catalog:update_product_views' product.pk %}" class="btn btn-outline-secondary">Редактировать</a>
                        <a href="{% url 'catalog:delete_product_views' product.pk %}" class="btn btn-outline-secondary">Удалить</a>
                    </div>
                    <div>
                        <form method="post" action="{% url 'catalog:unpublished_product_views' product.id %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-secondary" type="submit">Отмена публикации</button>
                        </form>
                    </div>
                    {% elif perms.product.can_unpublished_product or perms.product.delete_product %}
                    <div>
                        <form method="post" action="{% url 'catalog:unpublished_product_views' product.id %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-secondary" type="submit">Отмена публикации</button>
                        </form>
                    </div>
                    {% else %}
                    <a href="{% url 'catalog:home_views' %}" class="btn btn-outline-secondary">Назад</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-5">
    <div class="card-body">
        <h4 class="card-title text-start" style="margin-top:150px">{{ product.name }}</h4>
        <p class="card-text">{{ product.description }}</p>
        <a href="#" class="btn btn-primary">Купить {{product.price}}p.</a>
    </div>
</div>
{% endblock %}

web_shop/catalog/templates/catalog/unauthorized_user.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Каталог товаров{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css"/>
    <style>
        .high {
            height: 100vh;
        }
        .margin-top-main {
            margin-top: 100px;
        }
    </style>
</head>
<body>
<h1 class="text-center margin-top-main mb-5">Каталог товаров</h1>
<div class="text-center">
    <p> Для использования навигации по сайту или просмотра товаров необходимо
        <a href="{% url 'auth_users:login_views' %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
            атворизоваться
        </a> или
        <a href="{% url 'auth_users:register_views' %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
            зарегистрироваться
        </a>, если вы этого ещё не сделали.
    </p>
</div>
<div class="row">
    {% for product in products %}
    <div class="col-4 mb-5 d-flex justify-content-evenly">
        <div class="card" style="width: 300px;">
            <img src="{{product.image.url}}" class="card-img-top"
                 alt="...">
            <div class="card-body">
                <h4>
                    <p class="card-text"> {{ product.name }}. </p>
                </h4>
                <p class="card-text">{{ product.description }}.</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<script src="/static/js/bootstrap.bundle.min.js">
</script>
</body>
</html>