web_shop/app_like_photo/urls.py
from django.urls import path

from . import views

app_name = "app_like_photo"

urlpatterns = [
    path("main_views/", views.PostListView.as_view(), name="main_views"),
    path("post_views/<int:pk>/", views.PostDetailView.as_view(), name="post_views"),
    path("add_post_views/", views.PostCreateView.as_view(), name="add_post_views"),
    path("update_post_views/<int:pk>/", views.PostUpdateView.as_view(), name="update_post_views"),
    path("post_views/<int:pk>/delete_post_views/", views.PostDeleteView.as_view(), name="delete_post_views"),
]

web_shop/catalog/urls.py
from django.urls import path

from . import views

app_name = "catalog"

urlpatterns = [
    path("home_views/", views.ProductListView.as_view(), name="home_views"),
    path("contact_views/", views.ContactTemplateView.as_view(), name="contact_views"),
    path("category_views/", views.CategoryListView.as_view(), name="category_views"),
    path("catalog_views/", views.CatalogProductListView.as_view(), name="catalog_views"),
    path("product_views/<int:pk>/", views.ProductDetailView.as_view(), name="product_views"),
    path("add_product_views/", views.ProductCreateView.as_view(), name="add_product_views"),
    path("update_product_views/<int:pk>/", views.ProductUpdateView.as_view(), name="update_product_views"),
    path(
        "product_views/<int:pk>/delete_product_views/", views.ProductDeleteView.as_view(), name="delete_product_views"
    ),
    path("unauthorized_user_views/", views.UnauthorizedUserListView.as_view(), name="unauthorized_user_views"),
    path("profile_views/<int:pk>/", views.ProfileDetailView.as_view(), name="profile_views"),
    path("update_profile_views/<int:pk>/", views.ProfileUpdateView.as_view(), name="update_profile_views"),
    path("popup_question_views/<int:pk>/", views.ProfilePopupTemplateView.as_view(), name="popup_question_views"),
    path(
        "unpublished_product_views/<int:pk>/", views.UnpublishedProductView.as_view(), name="unpublished_product_views"
    ),
    path("category_detail_views/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail_views"),
]

web_shop/web_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("", include("app_like_photo.urls", namespace="app_like_photo")),
    path("", include("auth_users.urls", namespace="auth_users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_shop/app_like_photo/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    header = models.CharField(max_length=100, verbose_name="Заголовок поста")
    content = models.CharField(max_length=1000, verbose_name="Описание")
    image = models.ImageField(upload_to="photos/", verbose_name="Изображение")
    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")
    is_active = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return f"{self.header}"

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"
        db_table = "posts"

web_shop/app_like_photo/forms.py
from django import forms

from .models import Post


class FormForCreate(forms.ModelForm):
    header = forms.CharField(
        label="Наименование", widget=forms.TextInput(attrs={"class": "form-control", "style": "width: 400px"})
    )
    content = forms.CharField(
        label="Описание", widget=forms.Textarea(attrs={"class": "form-control", "style": "height: 100px"})
    )
    image = forms.ImageField(label="Изображение", widget=forms.FileInput(attrs={"class": "form-control"}))

    is_active = forms.BooleanField(label="Активность публикации", required=False)

    class Meta:
        model = Post
        fields = ["header", "content", "image", "is_active"]

web_shop/app_like_photo/views.py
import datetime

from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from web_shop.settings import EMAIL_SENDER

from .forms import FormForCreate
from .models import Post

# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = "app_like_photo/main.html"
    context_object_name = "posts"

    def get_queryset(self):
        # Получаем только активные объекты
        return Post.objects.filter(is_active=True)


class PostDetailView(DetailView):
    model = Post
    template_name = "app_like_photo/post.html"
    context_object_name = "post"

    def created_at_post(self):
        created_at_post = self.object.created_at
        time = datetime.date.today() - created_at_post
        if time.days == 0:
            result = "сегодня"
        elif time.days == 1:
            result = "вчера"
        else:
            result = f"{time.days} дней(дня) назад"
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["created_at_post"] = self.created_at_post()
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        if self.object.views_count == 10:
            send_mail(
                "от like_photo",
                f"Поздравляем, ваша публикация {self.object.header} набрала 100 просмотров",
                EMAIL_SENDER,
                ["serega94nn@yandex.ru"],
            )
        return self.object


class PostCreateView(CreateView):
    model = Post
    form_class = FormForCreate
    template_name = "app_like_photo/form_add_post.html"
    success_url = reverse_lazy("app_like_photo:main_views")


class PostUpdateView(UpdateView):
    model = Post
    form_class = FormForCreate
    template_name = "app_like_photo/form_add_post.html"

    def get_success_url(self):
        return reverse_lazy("app_like_photo:post_views", args=[self.kwargs.get("pk")])


class PostDeleteView(DeleteView):
    model = Post
    template_name = "app_like_photo/delete_post.html"
    success_url = reverse_lazy("app_like_photo:main_views")

web_shop/app_like_photo/templates/app_like_photo/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Bootstrap demo{% endblock %}</title>
        <link  rel="stylesheet" href="/static/css/bootstrap.min.css"/>
        <style>
            .high {
                height: 100vh;
            }
            .margin-top-main {
                margin-top: 100px;
            }
        </style>
    </head>
    <body>
        <div class="row">
            <div class="col-2">
                {% include 'app_like_photo/nav_bar.html' %}
            </div>
            <div class="col-10">
                {% block content %}{% endblock %}
            </div>
        </div>
        <script src="/static/js/bootstrap.bundle.min.js">
        </script>
    </body>
</html>

web_shop/app_like_photo/templates/app_like_photo/delete_post.html
<!-- delete_post.html -->
{% extends 'app_like_photo/base.html' %}

{% block title %}Удалить пост{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Удалить пост</h1>
    <p>Вы уверены, что хотите удалить пост?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a href="{% url 'app_like_photo:post_views' post.pk %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>

{% endblock %}

web_shop/app_like_photo/templates/app_like_photo/form_add_post.html
<!--form_add_product-->
{% extends 'app_like_photo/base.html' %}

{% block title %}Добавить пост{% endblock %}

{% block content %}

<div class="container" style="margin-top:20px">
    <form class="form-control border" style="width: 600px" method="post" enctype="multipart/form-data">
        {% if post %}
        <h5 class="text-center border-bottom pb-2">Изменить пост</h5>
        {% else %}
        <h5 class="text-center border-bottom pb-2">Добавить пост</h5>
        {% endif %}
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-2">Отправить</button>
    </form>
</div>
{% endblock %}

web_shop/app_like_photo/templates/app_like_photo/main.html
<!-- main.html -->
{% extends 'app_like_photo/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}

<h1 class="text-center margin-top-main">История публикаций</h1>

{% for post in posts %}
<div class="mb-5 d-flex justify-content-evenly">
    <div class="card" style="width: 350px; margin-top:20px">
        <h4 class="text-center">{{post.header}}</h4>
        <img src="{{post.image.url}}" class="card-img-top" alt="Изображение">
        <div class="card-body">
            <div class="row">
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'app_like_photo:post_views' post.pk %}"
                       class="btn btn-outline-secondary">Посмотреть</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endfor %}


{% endblock %}

web_shop/app_like_photo/templates/app_like_photo/nav_bar.html
<!--nav_bar-->

<nav class="navbar sticky-top bg-body-tertiary">
    <div class="container-xxl bg-dark rounded-start text-top" style="height:100vh">
        <a class="navbar-brand link-light border-bottom h4 pb-2 mb-2 border-opacity-50 border-light col-12"
           href="{% url 'app_like_photo:main_views' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                 class="bi bi-bootstrap align-top" viewBox="0 0 16 16">
                <path d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377z"/>
                <path d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3z"/>
            </svg>
            <span class="">Меню</span>
        </a>
        <ul class="nav flex-column margin-bottom">
            <li class="nav-item">
                <a class="nav-link active link-light" aria-current="page" href="{% url 'app_like_photo:main_views' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-house" viewBox="0 0 16 16">-->
                        <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5z"/>
                    </svg>
                    <span class="fs-6">Главная</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link link-light" href="{% url 'app_like_photo:add_post_views' %}">
                    <img src="/media/photos/add_card_24dp_E8EAED_FILL0_wght400_GRAD0_opsz24.png" width="20" height="20">
                    <span class="fs-6">Добавить пост</span>
                </a>
            </li>
        </ul>
        <div class="dropup-center dropup border-top h4 pt-3 mt-3 border-opacity-50 border-light col-12">
            <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://avatars.mds.yandex.net/get-entity_search/5283930/952851227/S600xU_2x"
                     class="rounded-circle" alt="..." width="30">
                Пользователь
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Профиль</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Выход</a></li>
            </ul>
        </div>
    </div>
</nav>

web_shop/app_like_photo/templates/app_like_photo/paginator.html
<!--paginator-->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a></li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Назад</span>
            </li>
        {% endif %}

        {% for num_page in page_obj.paginator.page_range %}
            {% if num_page == page_obj.number %}
                <li class="page-item active"><a class="page-link" href="#">{{ num_page }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a></li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link">Вперед</span>
            </li>
        {% endif %}
    </ul>
</nav>

web_shop/app_like_photo/templates/app_like_photo/post.html
<!-- main.html -->
{% extends 'app_like_photo/base.html' %}

{% block title %}Публикация{% endblock %}

{% block content %}

<h1 class="text-center margin-top-main"></h1>
<div class="row">
    <div class="mb-5 d-flex justify-content-evenly">
        <div class="card" style="width: 450px; margin-top:20px">
            <h4 class="text-center">{{post.header}}</h4>
            <img src="{{post.image.url}}" class="card-img-top" alt="Изображение">
            <div class="card-body">
                <p class="card-text text-center">{{ post.content }}</p>
                <div class="row">
                    <div class="btn-group" role="group" aria-label="Basic outlined example">
                        <a href="{% url 'app_like_photo:main_views' %}" class="btn btn-outline-secondary">Назад</a>
                        <a href="{% url 'app_like_photo:update_post_views' post.pk %}"
                           class="btn btn-outline-secondary">Изменить</a>
                        <a href="{% url 'app_like_photo:delete_post_views' post.pk %}" class="btn btn-outline-secondary">Удалить</a>
                    </div>
                    <small>Опубликовано: {{ created_at_post }}</small>
                    <small>Просмотров: {{ post.views_count }}</small>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}